### PR TITLE
Update Havemeyer 309 priority list.

### PR DESCRIPTION
**Pull request by kevin1**
Havemeyer 309 seating has the bottom part, and the balcony (top part).
The top part is more steep and easier to copy between rows, so we
really don't want seating to be dense there. Also it is more
disruptive to have TAs walk through it during the exam, and some side
parts of the balcony are totally impractical to access.

Assignment strategy:

- Fill every other seat in bottom part in columns (checkerboard
  pattern would allow cross-row copying)
- Every other seat of every other row in top part
- Double up students in the bottom part, starting in the front
- Previously skipped rows in the top part, center first
- Any remaining seats

### CODE REVIEW

**Comment by chmullig** [comment]
I woulda bet money nobody ever looked at this code after I left. 😎

**Comment by kevin1** [comment]
@garymlin and I have been looking at it! Saves us so much time. Also, the algorithm is pretty elegant - gets 90% of the way there with surprisingly little code.

**Comment by garymlin** [comment]
Please give no credit to me.  @kevin1 has done all the grunt work.

**Comment by garymlin** [comment]
LGTM

**Comment by kevin1** [comment]
made a minor change to priority list - can i get another ship it?

**Comment by danhcole** [comment]
LGTM -- how did you get they desk layout info for lefty desks?

**Comment by kevin1** [comment]
looked at every desk in havemeyer 309, lol

**Pull request merged**
